title: Bloghore
description: Blog seputar blockchain, crypto, web3, tech, dan ekonomi
baseurl: "" # Kosongkan jika di root domain
url: "https://bloghore.netlify.app" # Ganti sesuai domain kamu

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title/

defaults:
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: ""
    values:
      lang: id

collections:
  categories:
    output: true
    permalink: /category/:path/
